version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: ledger-postgres
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledgeruser
      POSTGRES_PASSWORD: ledgerpass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
